### ISSUE TITLE
Calibration status not clear when redoing

### ISSUE THREAD

**Issue by Mike4U** [nanovna/NanoVNA-V2-firmware#15]
git-20200507-7980406
The open, short,load,thru buttons correctly highlight when they're done.  However when you redo one of these there is no indication it has started or when it's done.

Perhaps pressing a highlighted ops,l,t button should unhighlight it until it is finished again.

**Comment by DiSlord** [comment]
You not fully fix this issue, i fix it in
This commit from my patch 
https://github.com/nanovna/NanoVNA-V2-firmware/pull/23/commits/3f7691beb30e621bd9193993d32c1f8ec69cbef0
For new UI
https://github.com/nanovna/NanoVNA-V2-firmware/pull/23

**Comment by douardda** [comment]
Since @DiSlord PR has been merged, can this issue be closed now?

**Comment by DiSlord** [comment]
I think yes. Now calibration show SOLT status, and it update on made.

**Comment by Mike4U** [comment]
The 20200525 release does not fix the issue.  Also a 20200617 version gabriel linked somewhere does not fix.  I haven't tried to compile the DiSlord merge.  Is a binary available somewhere?

**Comment by DG9BFC** [comment]
issue can be closed

**Comment by Mike4U** [comment]
Seems to be fixed in git 20201013-32077fd.

thanks
