### ISSUE TITLE
CW-Signal generation is not continous

### ISSUE THREAD

**Issue by zarath** [nanovna/NanoVNA-V2-firmware#3]
Don't know if it is a bug, but if S-A-A-2 is in CW Mode it only sends 
bursts of 5ms with pauses of 8ms
![DS1Z_QuickPrint2](https://user-images.githubusercontent.com/912565/79764057-279f4780-8325-11ea-9a2e-52c5e68f3db9.png)

**Comment by nanovna** [comment]
Yes, it has to change SW_ECAL to open circuit (see diagram in user guide) to measure the reference channel. I can add a signal generator mode but it wouldn't be able to measure S11 or S21 in this mode without large errors.

**Comment by zarath** [comment]
That would be a handy option. I think it should be mentioned in the user handbook, as S-A-A-2 differs in this regard to V1

**Comment by symcool** [comment]
I am looking forward to it being able to output a single frequency source

**Comment by ok1vaw** [comment]
I can confirm the problem with the CW, which is not CW but switched  pulse AM. I am looking forward to output single CW frequency and use the V2 as a true CW generator.

**Comment by helmarw** [comment]
agree, a CW signal generator option would be nice, even if it doesn't measure S11 properly...
would be also nice to have a few waveforms available like sine, square, triangle and sawtooth

**Comment by zarath** [comment]
> agree, a CW signal generator option would be nice, even if it doesn't measure S11 properly...
> would be also nice to have a few waveforms available like sine, square, triangle and sawtooth
The signal generation is done by some PLL devices (ADF4350 and Si5351). They onlly deliver clock
signals and aren't capable of waveform shaping. The NanoVNA-V2 is not an ARB

**Comment by ok1vaw** [comment]
Maybe even to extend the capability not only to CW generation, but 
adding a sweeper capability too with definable sweep time and frequency 
step would be quite usable. It is clear, that 10ms sweep, which is 
typical when using scalar generators will never be possible for 
measurement with the NanoVNA, but on my first view to the schematic the 
PLL setting is not a limiting factor, the loop is quite fast and I am 
convinced that hundred steps in 10ms could be sure possible.

This is an idea to extend the capability the NanoVNA to a great 
universal rf tool.

ok1vaw, Vojtech.

Dne 07.07.2020 v 9:58 Holger Müller napsal(a):

**Comment by zarath** [comment]
It should be fast enough for WSPR or FT-8 ;-)

**Comment by ok1vaw** [comment]
Do you mean to generate the WSPR or FT-8 directly by use the PLL inside the NanoVNA v2?

**Comment by zarath** [comment]
I wouldn't have any practical use, as it has no real time clock and FT-8 without receiving makes no sense.
Also signal filtering has to be added ....

**Comment by ok1vaw** [comment]
On the other hand having the possibility to have a real CW   or even true  sweep possibility would be great. Even if you could use it with external detector or a spectrum analyzer only.

**Comment by DG9BFC** [comment]
did any of you MEASURE ...or LISTEN to the cw signal??? it sounds very "rough" and wide now (i listen to it on 13cm)
my guess is that the reason for that signal to be so dirty is that the tcxo (main clock) does not have a clean power source ... 
by the way ... if there is a free dac pin left ... why not use a tuneable tcxo?!? 
can be calibrated and correction voltage stored in the device ...
if no free dac pin from mcu possible ... then a 10 turn trimmer and a tuneable tcxo
a really good one maybe costs another 10 bucks ... but i would pay that small extra fee and add a better tcxo plus a cleaner power source for it

**Comment by ok1vaw** [comment]
Up to the moment, when the switching will not be stopped you could not estimate too much about the quality of the CW signal. A good idea is to use Adisim PLL program from Analog Devices, which can model PLL noise, spectrum and tuning properties of all series of Analog Devices PLLs inclusive the noise of the XTAL oscillator. Adf4350 is used with a wideband loop, which filters the noisy VCO. It achieves -80dBc/Hz in 10kHz distance when locked. It is not a nothing against the theory, that you have a plenty of noise in 3kHz channel of standard SSB radio (about -45dB below the carrier peak). I agree that a noisy XTAL could the thing only worsen.

**Comment by wutje** [comment]
I think most people now already, but I created a version that has "continuous" CW
https://github.com/wutje/NanoVNA-V2-firmware/releases/tag/cw_mode_fix-beta.5
Please test this, if all is well I will create a pull request and we could have this fixed.

**Comment by DG9BFC** [comment]
can be closed

**Comment by zarath** [comment]
Yes, it's now continious, except for the first 2 measurements as mentioned.
I'll close that issue.
