### ISSUE TITLE
First S21 measurement out of tolerance

### ISSUE THREAD

**Issue by zarath** [nanovna/NanoVNA-V2-firmware#33]
When doing through measurements the first measured point is out of tolerance.

![IMG_20200803_180837](https://user-images.githubusercontent.com/912565/89203591-1b2dba80-d5b5-11ea-9ef5-4128eb349c7d.jpg)

Worked around in NanoVNASaver by dropping first point of a sweep

**Comment by DG9BFC** [comment]
i think this is also fixed

**Comment by zarath** [comment]
Yes that problem is solved.
