### ISSUE TITLE
Dmesg Always prompt "LIBOPENCM3 DID NOT ENABLE FPU!"

### ISSUE THREAD

**Issue by lzqgdt** [nanovna/NanoVNA-V2-firmware#38]
I thinks this is logical error. main2.cpp +1148 should chang to if(!cpu_enable_fpu()) .

**Comment by wutje** [comment]
Yes, but only if you compile with FPU enabled right?

**Comment by lzqgdt** [comment]
> Yes, but only if you compile with FPU enabled right?

Hello，Wutje ,It's seem work ,  Change Makefile to "DEVICE = gd32f303cc" .  Or maybe it is wrong way ?
