### ISSUE TITLE
Tag and publish a new version of the  firmware

### ISSUE THREAD

**Issue by douardda** [nanovna/NanoVNA-V2-firmware#41]
there have quite some nice work merged since last published version, it would be nice to make a new release now.

**Comment by gabriel-tenma-white** [comment]
The hardware related code is still in a bit of a mess right now since I'm finishing up support for plus and plus4, but I should be able to get everything in shape next week and do a new release with support for 4 hardware variants (V2_2, V2_2 with ST7796, V2 Plus, V2 Plus4).

**Comment by douardda** [comment]
ok thanks.

**Comment by DG9BFC** [comment]
just tested release from you david
at least it did not blow up the device hi hi
seems to work fine ... hopefully we see regular updates if changes have been made ... not only source but also releases
greetz dg9bfc sigi

**Comment by douardda** [comment]
@gabriel-tenma-white looks you have published a few new releases, thanks. Let's close this issue then.
