### ISSUE TITLE
Led lights

### ISSUE THREAD

**Issue by eried** [nanovna/NanoVNA-V2-firmware#42]
Hi, I am trying to make an improved 3d printable case for the v2 and I am wondering how important are all the lights on the back for users of the v2? 

Do you actually every look at them?

**Comment by gabriel-tenma-white** [comment]
The 4 LEDs just indicate battery status (there isn't a battery indicator on the display). I think you don't need to put holes there because most 3D printing material are translucent anyway.

**Comment by eried** [comment]
The purpleish metallic I used is now, but is awesome 😍 how about the other light? Are useful for something besides debugging?

**Comment by gabriel-tenma-white** [comment]
Other than the 4 battery indicator LEDs there are 2 LEDs for synthesizer lock, a red one for ADC clip, and a blue one controlled by the MCU that's currently not used for anything (it just flashes during plotting to show how long the code takes to execute).

**Comment by eried** [comment]
Thanks for the answer :) 

Anyone else uses the leds for something?
Do people actually check battery using the leds? 

I am still wondering if I should add the holes 🤔 beauty vs function?

**Comment by eried** [comment]
At the end I made both version, with or without holes for leds :)
https://www.thingiverse.com/thing:4592730

![image](https://user-images.githubusercontent.com/1091420/92666543-d579b580-f309-11ea-9347-9a068cecdd16.png)

![image](https://user-images.githubusercontent.com/1091420/92666694-40c38780-f30a-11ea-8d23-c2b4170512fb.png)
