### ISSUE TITLE
add more memories

### ISSUE THREAD

**Issue by DG9BFC** [nanovna/NanoVNA-V2-firmware#49]
i do not know if there is enough room left in the chip
we now have calibration 0-4 (5 memory) ... 0 i loaded on startup 
i love that option ... grin ... but could the soft remember what last memory was used (say you used memory 3 then on next startup 3 is used again)?!?
but back to my question ... can we have two more calibration memory??
on screen is room for another two ... so if there is enough room iside the chip to store calibrations then please add two more cal memory

**Comment by gabriel-tenma-white** [comment]
There is some flash space left, but these things compete for the remaining flash space:
- Full enhanced response cal (adds one more trace to all cal slots)
- 301 point sweep (1.5x the space needed)
- More cal slots
- More firmware features (code)

I will prioritize the first 2 features, and then use the remaining space for more cal slots. Saving which slot was last used does not use more flash and can be implemented.

**Comment by DG9BFC** [comment]
hi gabriel .. tnx fer answer .. so that means add the first two ... and if some room left we may add slot 5 and maybe 6 ?? fine ...
can you add the "use last slot" function in one of the next releases?? i guess its very practical to reopen the last one and not only slot 0
store a calibration for 2m, 70cm, 23cm, 13cm, 9cm (all 5 slots used) ... and if you allways use the same test cables you easy can reuse that calibration
... aehem .. v2plu4 has 401 points ... is there a bigger cpu inside with more space? or is the space all used in the plus fw? ( i drop you a direct mail ... i have a few questions about the plus .....)

**Comment by DG9BFC** [comment]
i have overflown your last commits ... guess we will soon have a new fw?

**Comment by DG9BFC** [comment]
hello gabriel
thanks for adding more slots :-)
but now no name or list is shown so i make another issue open for that
(in a minute or two)
so THIS issue closed
