### ISSUE TITLE
20200926 release with SAAS V2

### ISSUE THREAD

**Issue by jmseight** [nanovna/NanoVNA-V2-firmware#50]
I have a SAAS V2 NanoVNA.  It does work the binary-ili9341.bin version worked.  For all of the small screen 20200926 versions, they had problems with the location of the menu.  When touching the screen the menu popped up.  But after that the clocking on the screen actually registered on what I can gather as the diagonally opposite area on the screen.

I tried: 
nanovna-v2-20200926-v2_2.bin
nanovna-v2-20200926-v2_3.2.bin
nanovna-v2-20200926-v2_2.8.bin

Thanks,
James

**Comment by gabriel-tenma-white** [comment]
You need to do touch cal because updating the firmware clears the config.
Use the 3 pushbuttons to navigate the menu to CONFIG > TOUCH CAL, then follow on-screen instructions.

Are you using the 3.2 inch version? If so can you tell me the 4 "touch cal" values in CONFIG > DMESG after doing a touch calibration so I can incorporate it into the default touch cal for this variant?

**Comment by DG9BFC** [comment]
hi gabriel
i have a 4 inch modded v2 and an saa2n (basically same thing now besides button location and n sockets adaptor) .. do you need the values for those displays??
i allways make a touch cal after fw upgrade cause i prefer to have sockets point upwards (flip display) ... but if you need the values (to add default calib in non flipped state) i can flip display ... do a touch cal a few times and then sernd you the values (a few calibs to have a value range and use mid value as default) ... and i can do that on BOTH units (guessing that also the touch has some spreading in those values)
so if you need those numbers ... drop me a note (as you know i like to experiment and i wanna help if i can ... most of the time its a winwin result at the end)

**Comment by jmseight** [comment]
Hi,
I tried nanovna-v2-20200926-v2_2.bin and used the cal and got it to work well.  I am not sure what HW I have so I then downloaded nanovna-v2-20200926-v2plus.bin, and it works as well, without the re-calibration.  The calibration is
116, 151
86, 117
Is there a way to tell the difference between the V2.2 and V2plus (V2.3) HW?
Thanks,
James

**Comment by jmseight** [comment]
Confirmed my nanovna should be v2.2.  uploaded the 2.2 sw again and calibration stayed.  signal sweep was slower but much less noisy.  The calibration are:
116, 151
86, 117
