### ISSUE TITLE
Moving a marker back and forth crashes  VNA

### ISSUE THREAD

**Issue by Mike4U** [nanovna/NanoVNA-V2-firmware#57]
in git 20201013-32077fd
Grab any marker with wand and move back and forth about 3 times will cause crash.
Stay on left side of screen to avoid menu pop-up.
Pause Sweep on or off doesn't matter.
Moving markers with buttons is ok.

**Comment by JohnOH** [comment]
I too have experienced this "crash". In my case the code hangs, requiring a power cycle to recover the UI.

**Comment by DG9BFC** [comment]
this bug seems to be solved with last fw from dislord ... i guess very soon you see that fw for all users (it was tested in nanovna beta test group)

**Comment by Mike4U** [comment]
Tried git-20201031-dc07fe5 which I think includes dislord changes and the hang remains.

**Comment by Mike4U** [comment]
Can confirm that pull request #60 would fix the problem.

**Comment by Mike4U** [comment]
Merge of #60 fixed the issue.  Thanks, works even better now.
